using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

public static class SpawnGrassCleanup
{
    const string ScenePath = "Assets/_RPG/Scenes/SpawnVillage.unity";
    const string RequestPath = "Assets/_RPG/Generated/CleanupSpawnGrass.generate";
    const string GeneratedRootName = "SpawnGrass_AutoGenerated";
    const string GrassPrefabPath =
        "Assets/Proxy Games/Stylized Nature Kit Lite/Prefabs/Foliage/Grass/Grass.prefab";
    const float FountainGrassRadius = 12f;

    [MenuItem("RPG/World/Keep Grass Only Around Spawn Fountain")]
    public static void Clean()
    {
        if (EditorApplication.isPlayingOrWillChangePlaymode)
            return;

        if (EditorSceneManager.GetActiveScene().path != ScenePath)
            EditorSceneManager.OpenScene(ScenePath);

        Transform fountain = FindSpawnFountain();
        if (fountain == null)
        {
            Debug.LogError("[SpawnGrassCleanup] No se encontró la fuente del spawn. No se eliminó ningún objeto.");
            return;
        }

        Vector3 fountainCenter = GetVisualCenter(fountain);
        var candidates = new List<GameObject>();
        foreach (Transform current in Object.FindObjectsByType<Transform>(
                     FindObjectsInactive.Include))
        {
            if (current == null || !IsGeneratedGrass(current.gameObject))
                continue;
            candidates.Add(current.gameObject);
        }

        int removed = 0;
        int preserved = 0;
        foreach (GameObject grass in candidates)
        {
            if (grass == null)
                continue;

            Vector3 delta = grass.transform.position - fountainCenter;
            delta.y = 0f;
            if (delta.sqrMagnitude <= FountainGrassRadius * FountainGrassRadius)
            {
                preserved++;
                continue;
            }

            Object.DestroyImmediate(grass);
            removed++;
        }

        GameObject generatedRoot = GameObject.Find(GeneratedRootName);
        if (generatedRoot != null && generatedRoot.transform.childCount == 0)
            Object.DestroyImmediate(generatedRoot);

        EditorSceneManager.MarkSceneDirty(EditorSceneManager.GetActiveScene());
        EditorSceneManager.SaveScene(EditorSceneManager.GetActiveScene());
        Debug.Log($"[SpawnGrassCleanup] Pasto repetido limpiado. Eliminados: {removed}. " +
                  $"Conservados alrededor de la fuente: {preserved}. Radio: {FountainGrassRadius:0} m.");
    }

    static bool IsGeneratedGrass(GameObject candidate)
    {
        if (candidate == null)
            return false;

        Transform root = candidate.transform;
        while (root != null)
        {
            if (root.name == GeneratedRootName)
                return candidate.name.StartsWith("Grass", System.StringComparison.OrdinalIgnoreCase) &&
                       candidate.GetComponentInChildren<Renderer>(true) != null;
            root = root.parent;
        }

        string prefabPath = PrefabUtility.GetPrefabAssetPathOfNearestInstanceRoot(candidate);
        return prefabPath.Replace('\\', '/')
            .Equals(GrassPrefabPath, System.StringComparison.OrdinalIgnoreCase);
    }

    static Transform FindSpawnFountain()
    {
        Vector3 spawn = Vector3.zero;
        GameObject spawnPoint = GameObject.FindWithTag("SpawnPoint");
        if (spawnPoint != null)
            spawn = spawnPoint.transform.position;
        else
        {
            GameObject player = GameObject.FindWithTag("Player");
            if (player != null)
                spawn = player.transform.position;
        }

        Transform best = null;
        float bestDistance = float.PositiveInfinity;
        foreach (Transform current in Object.FindObjectsByType<Transform>(
                     FindObjectsInactive.Include))
        {
            string lower = current.name.ToLowerInvariant();
            if (!lower.Contains("fountain") && !lower.Contains("fuente"))
                continue;

            float distance = (current.position - spawn).sqrMagnitude;
            if (distance >= bestDistance)
                continue;
            best = current;
            bestDistance = distance;
        }
        return best;
    }

    static Vector3 GetVisualCenter(Transform root)
    {
        Renderer[] renderers = root.GetComponentsInChildren<Renderer>(true);
        if (renderers.Length == 0)
            return root.position;

        Bounds bounds = renderers[0].bounds;
        for (int i = 1; i < renderers.Length; i++)
            bounds.Encapsulate(renderers[i].bounds);
        Vector3 center = bounds.center;
        center.y = root.position.y;
        return center;
    }

    [InitializeOnLoadMethod]
    static void Queue() => EditorApplication.delayCall += TryRun;

    static void TryRun()
    {
        string request = Path.GetFullPath(RequestPath);
        if (!File.Exists(request))
            return;
        if (EditorApplication.isPlayingOrWillChangePlaymode)
        {
            EditorApplication.delayCall += TryRun;
            return;
        }

        File.Delete(request);
        if (File.Exists(request + ".meta"))
            File.Delete(request + ".meta");
        Clean();
    }
}
