using System.IO;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

public static class SpawnGrassGenerator
{
    const string ScenePath = "Assets/_RPG/Scenes/SpawnVillage.unity";
    const string RequestPath = "Assets/_RPG/Generated/SpawnGrass.generate";
    const string GrassPrefabPath = "Assets/Proxy Games/Stylized Nature Kit Lite/Prefabs/Foliage/Grass/Grass.prefab";
    const string RootName = "SpawnGrass_AutoGenerated";

    const int Seed = 40704;
    const float SpawnRadius = 72f;
    const float GridSpacing = 2.45f;
    const float Density = 0.82f;
    const float PathClearance = 0.28f;
    const float ObjectClearance = 1.15f;

    static readonly float[] SpawnPathAngles = { -48f, 36f, 123f, -150f, 172f, -8f };

    [MenuItem("RPG/World/Generate Spawn Grass")]
    public static void Generate()
    {
        if (EditorApplication.isPlayingOrWillChangePlaymode)
        {
            Debug.LogWarning("[SpawnGrassGenerator] Sali de Play Mode para generar pasto.");
            return;
        }

        if (EditorSceneManager.GetActiveScene().path != ScenePath)
            EditorSceneManager.OpenScene(ScenePath);

        GameObject grassPrefab = AssetDatabase.LoadAssetAtPath<GameObject>(GrassPrefabPath);
        if (grassPrefab == null)
        {
            Debug.LogError("[SpawnGrassGenerator] No encontre el prefab Grass: " + GrassPrefabPath);
            return;
        }

        Random.InitState(Seed);
        RemovePreviousRoot();

        Terrain terrain = Terrain.activeTerrain;
        Vector3 center = FindSpawnCenter();
        GameObject root = new GameObject(RootName);

        int placed = 0;
        int skippedPath = 0;
        int skippedObjects = 0;

        for (float x = -SpawnRadius; x <= SpawnRadius; x += GridSpacing)
        {
            for (float z = -SpawnRadius; z <= SpawnRadius; z += GridSpacing)
            {
                Vector2 jitter = Random.insideUnitCircle * (GridSpacing * 0.44f);
                Vector3 pos = new Vector3(center.x + x + jitter.x, 0f, center.z + z + jitter.y);
                Vector2 flat = new Vector2(pos.x - center.x, pos.z - center.z);
                if (flat.magnitude > SpawnRadius || Random.value > Density)
                    continue;

                if (IsPath(pos, terrain, center))
                {
                    skippedPath++;
                    continue;
                }

                pos = Grounded(pos, terrain);
                if (IsBlockedBySceneObject(pos))
                {
                    skippedObjects++;
                    continue;
                }

                GameObject grass = (GameObject)PrefabUtility.InstantiatePrefab(grassPrefab);
                grass.name = "Grass";
                grass.transform.SetParent(root.transform, true);
                grass.transform.SetPositionAndRotation(pos, Quaternion.Euler(0f, Random.Range(0f, 360f), 0f));
                float scale = Random.Range(0.78f, 1.32f);
                grass.transform.localScale = Vector3.one * scale;
                placed++;
            }
        }

        EditorSceneManager.MarkSceneDirty(EditorSceneManager.GetActiveScene());
        EditorSceneManager.SaveScene(EditorSceneManager.GetActiveScene());
        Debug.Log($"[SpawnGrassGenerator] Pasto generado: {placed}. Caminos evitados: {skippedPath}. Objetos evitados: {skippedObjects}.");
    }

    [InitializeOnLoadMethod]
    static void RunRequestedGeneration()
    {
        EditorApplication.delayCall += TryRunRequestedGeneration;
    }

    static void TryRunRequestedGeneration()
    {
        string absolutePath = Path.GetFullPath(RequestPath);
        if (!File.Exists(absolutePath) || EditorApplication.isPlayingOrWillChangePlaymode)
            return;

        File.Delete(absolutePath);
        string metaPath = absolutePath + ".meta";
        if (File.Exists(metaPath))
            File.Delete(metaPath);

        Generate();
    }

    static Vector3 FindSpawnCenter()
    {
        GameObject spawn = GameObject.FindWithTag("SpawnPoint");
        if (spawn != null)
            return spawn.transform.position;

        GameObject player = GameObject.FindWithTag("Player");
        if (player != null)
            return player.transform.position;

        return Vector3.zero;
    }

    static Vector3 Grounded(Vector3 position, Terrain terrain)
    {
        if (terrain != null)
        {
            position.y = terrain.SampleHeight(position) + terrain.transform.position.y + 0.02f;
            return position;
        }

        if (Physics.Raycast(position + Vector3.up * 80f, Vector3.down, out RaycastHit hit, 160f, ~0, QueryTriggerInteraction.Ignore))
            position.y = hit.point.y + 0.02f;
        return position;
    }

    static bool IsPath(Vector3 world, Terrain terrain, Vector3 center)
    {
        if (Vector2.Distance(new Vector2(world.x, world.z), new Vector2(center.x, center.z)) < 7.5f)
            return true;

        if (SpawnVillagePathMask(world.x - center.x, world.z - center.z) > PathClearance)
            return true;

        if (DistantPathMask(world.x, world.z) > 0.24f)
            return true;

        return TerrainLooksLikePath(world, terrain);
    }

    static bool TerrainLooksLikePath(Vector3 world, Terrain terrain)
    {
        if (terrain == null || terrain.terrainData == null || terrain.terrainData.terrainLayers == null)
            return false;

        TerrainData data = terrain.terrainData;
        Vector3 local = world - terrain.transform.position;
        if (local.x < 0f || local.z < 0f || local.x > data.size.x || local.z > data.size.z)
            return false;

        int ax = Mathf.Clamp(Mathf.RoundToInt((local.x / data.size.x) * (data.alphamapWidth - 1)), 0, data.alphamapWidth - 1);
        int az = Mathf.Clamp(Mathf.RoundToInt((local.z / data.size.z) * (data.alphamapHeight - 1)), 0, data.alphamapHeight - 1);
        float[,,] alpha = data.GetAlphamaps(ax, az, 1, 1);

        TerrainLayer[] layers = data.terrainLayers;
        for (int i = 0; i < layers.Length; i++)
        {
            if (alpha[0, 0, i] < 0.22f || layers[i] == null)
                continue;

            string name = layers[i].name.ToLowerInvariant();
            if (name.Contains("path") || name.Contains("road") || name.Contains("camino"))
                return true;
        }
        return false;
    }

    static bool IsBlockedBySceneObject(Vector3 position)
    {
        Collider[] hits = Physics.OverlapSphere(position + Vector3.up * 0.7f, ObjectClearance, ~0, QueryTriggerInteraction.Ignore);
        foreach (Collider hit in hits)
        {
            if (hit == null || hit is TerrainCollider)
                continue;

            string path = GetPath(hit.transform).ToLowerInvariant();
            if (path.Contains(RootName.ToLowerInvariant()) || path.Contains("grass") || path.Contains("terrain") || path.Contains("ground"))
                continue;

            return true;
        }
        return false;
    }

    static float SpawnVillagePathMask(float x, float z)
    {
        float angle = Mathf.Atan2(z, x) * Mathf.Rad2Deg;
        float radius = new Vector2(x, z).magnitude;
        float mask = 0f;
        foreach (float pathAngle in SpawnPathAngles)
            mask += PathBand(angle, radius, pathAngle, 7f, SpawnRadius + 8f, 5.8f);
        return Mathf.Clamp01(mask);
    }

    static float DistantPathMask(float x, float z)
    {
        float angle = Mathf.Atan2(z, x) * Mathf.Rad2Deg;
        float radius = new Vector2(x, z).magnitude;
        float mask =
            PathBand(angle, radius, -48f, 76f, 410f, 9.0f) +
            PathBand(angle, radius, 36f, 82f, 520f, 9.5f) +
            PathBand(angle, radius, 123f, 105f, 555f, 10f) +
            PathBand(angle, radius, -150f, 120f, 590f, 10f) +
            PathBand(angle, radius, 172f, 170f, 500f, 7.5f) +
            PathBand(angle, radius, -8f, 185f, 470f, 7.5f);
        return Mathf.Clamp01(mask);
    }

    static float PathBand(float angle, float radius, float targetAngle, float minRadius, float maxRadius, float width)
    {
        float angleDelta = Mathf.Abs(Mathf.DeltaAngle(angle, targetAngle + Mathf.Sin(radius * 0.018f) * 9f));
        float radial = Mathf.SmoothStep(0f, 1f, Mathf.InverseLerp(minRadius - 10f, minRadius + 12f, radius));
        radial *= 1f - Mathf.SmoothStep(0f, 1f, Mathf.InverseLerp(maxRadius - 10f, maxRadius + 18f, radius));
        return Mathf.SmoothStep(1f, 0f, Mathf.InverseLerp(width, width + 5.5f, angleDelta)) * radial;
    }

    static void RemovePreviousRoot()
    {
        GameObject oldRoot = GameObject.Find(RootName);
        if (oldRoot != null)
            Object.DestroyImmediate(oldRoot);
    }

    static string GetPath(Transform transform)
    {
        string path = transform.name;
        while (transform.parent != null)
        {
            transform = transform.parent;
            path = transform.name + "/" + path;
        }
        return path;
    }
}
